name: MinimizeFactions
main: com.minimize.factions.MinimizeFactionsPlugin
version: 1.0
author: minimize
api-version: 1.20
commands:
  factions:
    aliases: [f]
    description: Main command for MinimizeFactions
permissions:
  factions.use:
    default: true
  factions.admin:
    default: op
  factions.claim:
    default: op
  factions.points:
    default: op
  factions.tnt:
    default: op
  factions.check:
    default: op
